version: "3.4"

name: cuttle_back_net

services:

  infinite:
    image: debian:latest
    command: tail -f /dev/null
    networks:
      - cuttle_back_net


  dpg-cl3vl3quuipc738nqdhg-a:
    image: postgres:12-alpine3.14
    container_name: dpg-cl3vl3quuipc738nqdhg-a
    restart: on-failure
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: users_zvk1_user
      POSTGRES_PASSWORD: 4RaFYThOKEpSsFjQjFXgXrjPjKGK59Dp
    networks:
      - cuttle_back_net

  cuttle_back:
    container_name: cuttle_back
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 45s
    depends_on:
        - dpg-cl3vl3quuipc738nqdhg-a
    entrypoint: [ "java", "-Dspring.profiles.active=container", "-jar", "Cuttle-0.0.1-SNAPSHOT.jar" ]
    networks:
      - cuttle_back_net

volumes:
  postgresql:
  mariadb:



networks:
  cuttle_back_net:
    driver: bridge